[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "solvers command-line interface"

[[bin]]
name = "solvers"
path = "src/main.rs"

[dependencies]
abstraction = { workspace = true }
cards = { workspace = true }
engine = { workspace = true, features = ["serde"] }
formats = { workspace = true }
game = { workspace = true }
holdem = { workspace = true }
preflop = { workspace = true }
multiway = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
rayon = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tiny_http = { workspace = true }

toml = { workspace = true }
toml_edit = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
